/*

 TESTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 60 x 36
   Tile set      : Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __TestMap_h_INCLUDE
#define __TestMap_h_INCLUDE

#define TestMapWidth 60
#define TestMapHeight 36
#define TestMapBank 0

#define TestMap TestMapPLN0
extern const unsigned char TestMapPLN0[];
extern const unsigned char TestMapPLN1[];

#endif

/* End of TESTMAP.H */
